spring.application.name=movies
spring.datasource.url=jdbc:h2:file:./movies_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
# Просим Spring каждый раз обновлять структуру таблиц, если мы меняем код
spring.jpa.hibernate.ddl-auto=validate
# Просим выводить SQL-запросы в консоль, чтобы видеть, что происходит
spring.jpa.show-sql=true
spring.flyway.enabled=true
logging.level.org.flywaydb=DEBUG
spring.flyway.locations=classpath:db/migration
spring.security.user.name=admin
spring.security.user.password=supersecret